name: Run Unit Tests

on:
  push:
    branches: [ "**" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Debug import issue
      run: |
        echo "=== Project Structure ==="
        find . -name "*.py" | sort
        echo "=== Trying to import circle ==="
        python -c "import sys; print('Python path:', sys.path); from circle import area; print('Import successful!')" || echo "Import failed"
        echo "=== Testing circle functions ==="
        python -c "from circle import area, perimeter; print('Area of radius 5:', area(5)); print('Perimeter of radius 5:', perimeter(5))"
    
    - name: Run specific test file
      run: |
        PYTHONPATH=. python -m unittest tests.test_circle -v
