name: Run Unit Tests

on:
  push:
    branches: [ "**" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Debug project structure
      run: |
        echo "Project structure:"
        find . -name "*.py" | head -20
        echo "Current directory:"
        pwd
        ls -la
    
    - name: Install project
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Run unit tests
      run: |
        python -m unittest discover tests/ -v
