name: Run Unit Tests

on:
  push:
    branches: [ "**" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Debug test failure
      run: |
        echo "=== Running circle tests with detailed output ==="
        python -m unittest tests.test_circle -v || echo "Tests failed with exit code: $?"
        echo "=== Testing circle functions directly ==="
        python -c "
        from circle import area, perimeter
        print('Area of 5:', area(5))
        print('Perimeter of 5:', perimeter(5))
        print('Area of 0:', area(0))
        try:
            area(-1)
            print('ERROR: Negative radius should raise ValueError')
        except ValueError:
            print('OK: Negative radius correctly raises ValueError')
        "
    
    - name: Run all tests
      run: |
        python -m unittest discover tests/ -v
